# Import system
import sys
# Python Imports
# PySide6 Imports
from PySide6 import QtCore as Qtc
from PySide6 import QtWidgets as Qtw
from PySide6 import QtGui as Qtgui
# UI Imports
from Main.UI.main_window import Ui_mw_MainWindow
from Soil.soils_dialog import SoilsDialog
from Materials.materials_dialog import MaterialsDialog
#from Application_Login.login import LoginForm
#Custom Imports
from Database.db_functions import *
from Classes.Wall import Wall
from Classes.Soil import Soil
from Classes.Concrete import Concrete
from Classes.Rebar import Rebar

class MainWindow(Qtw.QMainWindow, Ui_mw_MainWindow):
    """
    Main application window class.
    Inherits from QMainWindow and the autogenerated Ui_mw_MainWindow.

    This class handles initializing the user interface, connecting menu actions,
    and setting up placeholders for forms, soil profiles, concrete properties, and rebar data.
    """

    def __init__(self):
        """
        Initialize the MainWindow instance.
        Sets up UI components, initializes internal properties, connects UI actions,
        and displays the main window.
        """
        super().__init__()

        # Setup the UI elements from the loaded UI file
        self.setupUi(self)

        # Placeholder properties for different forms and materials
        self.form = None  # Placeholder for a form (e.g., project form or input dialog)
        self.scene = Qtw.QGraphicsScene(self.gv_main_canvas)
        self.gv_main_canvas.setScene(self.scene)
        self.wall = None # Placeholder for the wall object
        self.soil = None  # Placeholder for soil profile information
        self.concrete = None  # Placeholder for concrete material information
        self.rebar_dict = {}  # Dictionary to hold rebar types and properties
        self.rebar_settings = {}  # Dictionary for additional rebar settings

        # Perform startup tasks (e.g., loading defaults or preparing the environment)
        self.start_up()

        # Connect menu actions to their corresponding slots
        self.connect_actions()

        # Display the main application window
        self.show()

    def connect_actions(self):
        self.a_defineSoil.triggered.connect(self.open_soils_dialog)  # "Define Soil" menu action
        self.a_defineMaterials.triggered.connect(self.open_materials_dialog)  # "Define Materials" menu action
        self.a_exit.triggered.connect(self.close)  # "Exit" menu action

    @Qtc.Slot()
    def open_soils_dialog(self) -> None:
        """
        Open the Soil Properties dialog window.

        Creates an instance of SoilsDialog using the current soil data.
        Connects the dialog's soil_updated signal to update the MainWindow's soil information.
        """
        self.form = SoilsDialog(self.soil)
        self.form.soil_updated.connect(self.update_soil)  # Connect dialog signal to update method
        self.form.show()  # Show the dialog

    @Qtc.Slot()
    def open_materials_dialog(self) -> None:
        """
        Open the Materials Properties dialog window.

        Creates an instance of MaterialsDialog using the current concrete and rebar data.
        Connects the dialog's materials_updated and rebar_updated signals to update methods.
        """
        self.form = MaterialsDialog(self.concrete, self.rebar_dict, self.rebar_settings)
        self.form.materials_updated.connect(self.update_concrete)  # Connect concrete update
        self.form.rebar_updated.connect(self.update_rebar)  # Connect rebar update
        self.form.show()  # Show the dialog

    @Qtc.Slot(list)
    def update_soil(self, new_soil: list) -> None:
        """
        Update soil properties based on data received from the SoilsDialog.

        Args:
            new_soil (list): A list containing updated soil properties in a fixed order.
        """
        # Update soil object attributes with values from the list
        self.soil.name = new_soil[0]
        self.soil.unit_weight = new_soil[1]
        self.soil.uls_bearing = new_soil[2]
        self.soil.sls_bearing = new_soil[3]
        self.soil.friction_coeff = new_soil[4]
        self.soil.active_coeff = new_soil[5]
        self.soil.passive_coeff = new_soil[6]

    @Qtc.Slot(list)
    def update_concrete(self, new_concrete: list) -> None:
        """
        Update concrete properties based on data received from the MaterialsDialog.

        Args:
            new_concrete (list): A list containing updated concrete properties in a fixed order.
        """
        # Update concrete object attributes with values from the list
        self.concrete.name = new_concrete[0]
        self.concrete.fc = new_concrete[1]
        self.concrete.unit_weight = new_concrete[2]
        self.concrete.density = new_concrete[3]

    @Qtc.Slot(list)
    def update_rebar(self, new_rebar: list) -> None:
        """
        Update rebar settings based on data received from the MaterialsDialog.

        Args:
            new_rebar (list): A list containing rebar selections and spacing values.
        """
        # Update rebar settings dictionary with selections and spacings
        self.rebar_settings['smallest_bar'] = self.rebar_dict[new_rebar[0]]
        self.rebar_settings['default_bar'] = self.rebar_dict[new_rebar[1]]
        self.rebar_settings['largest_bar'] = self.rebar_dict[new_rebar[2]]
        self.rebar_settings['min_spacing'] = new_rebar[3]
        self.rebar_settings['max_spacing'] = new_rebar[4]

    def start_up(self) -> None:
        """
        Perform startup tasks for the MainWindow.

        Connects to the settings database, retrieves default material properties (soil, concrete, rebar),
        initializes corresponding objects, and sets default rebar settings.
        """
        # Initialize Default Wall Object
        self.wall = Wall(1200, # grade difference
                         150, # wall thickness
                         300, # toe cover
                         1000, # footing width
                         300, # footing thickness
                         250 # toe length
        )

        # Set Initial Wall Properties to Slider and Assoiaed TextLables
        self.hs_wall_height.setValue(self.wall.grade_difference)
        self.tl_wall_height.setText(f"{str(self.wall.grade_difference)} mm")

        self.hs_wall_thickness.setValue(self.wall.thickness)
        self.tl_wall_thickness.setText(f"{str(self.wall.thickness)} mm")

        self.hs_footing_width.setValue(self.wall.footing_width)
        self.tl_footing_width.setText(f"{str(self.wall.footing_width)} mm")

        self.hs_footing_thickness.setValue(self.wall.footing_thickness)
        self.tl_footing_thickness.setText(f"{str(self.wall.footing_thickness)} mm")

        self.hs_toe_length.setValue(self.wall.toe_length)
        self.tl_toe_length.setText(f"{str(self.wall.toe_length)} mm")

        # Draw Wall
        self.draw_wall()

        # Connect to settings database
        settings_db = sql_connect('retain.db')

        # Retrieve default soil, concrete, and rebar data
        default_soil = return_data(settings_db['Connection'], settings_db['Cursor'], 'Soil')[0]
        default_concrete = return_data(settings_db['Connection'], settings_db['Cursor'], 'Concrete')[0]
        default_rebar = return_data(
            settings_db['Connection'],
            settings_db['Cursor'],
            'Rebar',
            ["Name", "Diameter", "Area", "Fy", "MOE"]
        )

        # Create Soil object using retrieved default values
        self.soil = Soil(
            default_soil[1],  # name
            default_soil[2],  # unit weight
            default_soil[3],  # ULS bearing resistance
            default_soil[4],  # SLS bearing resistance
            default_soil[5],  # friction coefficient
            default_soil[6],  # active earth pressure coefficient
            default_soil[7]   # passive earth pressure coefficient
        )

        # Create Concrete object using retrieved default values
        self.concrete = Concrete(
            default_concrete[1],  # name
            default_concrete[2],  # compressive strength (fc)
            default_concrete[3],  # unit weight
            default_concrete[4]   # density
        )

        # Create Rebar objects and populate rebar dictionary
        for bar in default_rebar:
            self.rebar_dict[bar[0]] = Rebar(
                bar[0],  # Name
                bar[1],  # Diameter
                bar[2],  # Area
                bar[3],  # Yield strength (Fy)
                bar[4]   # Modulus of Elasticity (MOE)
            )

        # Set default reinforcement settings
        self.rebar_settings['smallest_bar'] = self.rebar_dict['15M']
        self.rebar_settings['default_bar'] = self.rebar_dict['15M']
        self.rebar_settings['largest_bar'] = self.rebar_dict['25M']
        self.rebar_settings['min_spacing'] = 75  # Minimum spacing (mm)
        self.rebar_settings['max_spacing'] = 400 # Maximum spacing (mm)

    def draw_wall(self) -> None:
        """Draw the footing and wall on the graphics scene, and auto-fit it in the view."""
        if not self.wall:
            return

        self.scene.clear()

        print(self.gv_main_canvas.width(), self.gv_main_canvas.height())

        scaler = 0.35

        # --- Draw Footing at Real Dimensions (mm) ---
        footing_rect = self.wall.get_footing_rect(scaler)
        footing = Qtw.QGraphicsRectItem(footing_rect)
        footing.setBrush(Qtgui.QBrush(Qtgui.QColor("darkgray")))
        self.scene.addItem(footing)

        # --- Draw Wall ---
        wall_rect = self.wall.get_wall_rect(scaler)
        wall = Qtw.QGraphicsRectItem(wall_rect)
        wall.setBrush(Qtgui.QBrush(Qtgui.QColor("lightgray")))
        self.scene.addItem(wall)

        # --- Adjust Scene ---
        # Expand scene rect a little so it doesn't touch edges
        padding = 0  # mm padding around drawing
        bounding_rect = self.scene.itemsBoundingRect()
        expanded_rect = bounding_rect.adjusted(-padding, -padding, padding, padding)

        self.scene.setSceneRect(expanded_rect)

        # --- Fit View ---
        # self.gv_main_canvas.fitInView(expanded_rect, Qtc.Qt.AspectRatioMode.KeepAspectRatioByExpanding)


if __name__ == "__main__":
    # Create new QApplication instance
    app = Qtw.QApplication(sys.argv)
    # Create window object (could also be a widget)
    window = MainWindow()
    # Handle application shutdown
    sys.exit(app.exec())