[project]
name = "pyside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "pyside6==6.8.1",
    "rich>=13.9.4",
]

[tool.uv.workspace]
members = ["uic"]
